### ISSUE TITLE
Delete 'Annotate with [ItemCanBeNull/ItemNotNull]' quick action

### ISSUE THREAD

**Issue by zvirja** [prodot/ReCommended-Extension#20]
Starting R# 2016.2 there are built-in quick actions to arrange `[ItemNotNull]`/`[ItemCanBeNull]' attributes. Therefore, currently, there are duplicates in menu:

![image](https://cloud.githubusercontent.com/assets/1074182/17929100/f8293eec-6a06-11e6-9520-04c5cf185dca.png)

Moreover, R# supports both attributes, while plugin provides a half only.

**Comment by michael-damatov** [comment]
R# 2016.2 still doesn't support async methods where task result is a reference type:
`async Task<string> MethodAsync() => null; // [ItemNotNull] must be suggested`.

Removing the quick action would reduce the functionality.

**Comment by michael-damatov** [comment]
The upcoming release 4.0 does not suggest to annotate with `[ItemNotNull]` if the nullable annotation context is enabled (C# 8.0).
