### ISSUE TITLE
Make annotation actions consistent with default ones

### ISSUE THREAD

**Issue by zvirja** [prodot/ReCommended-Extension#22]
Please tune the `Annotate with ...` quick actions to look like embedded annotation actions:
1. Change text to not contain `Annotate with...` prefix. 
2. Change anchor to have the same position as default annotation actions.

Currently, they are placed in wrong place and that pollutes the user experience.

**Comment by michael-damatov** [comment]
The effort of implementing this clear outweighs the benefits.
