### ISSUE TITLE
Annotation actions: Add "Remove" action for all "Add" actions your have

### ISSUE THREAD

**Issue by zvirja** [prodot/ReCommended-Extension#23]
Please add "Remove" annotation actions each time you introduce annotate action.

For instance, you provide context action to put `Pure` or `InstantHandle` attribute, however there are no actions to remove them if they are already present. I believe that such actions should be present to make the usage experience consistent.

If there is a switch between values (e.g. `NotNull/CanBeNull`) add more rare option to sub-menu.

**Comment by michael-damatov** [comment]
Adding a corresponding "remove" action means adding a new code that detects contract statements already _added_. The effort of doing this overweights the benefits.
