### ISSUE TITLE
Don't warn about throwing Exception when not explicitly throwing Exception

### ISSUE THREAD

**Issue by cmeeren** [prodot/ReCommended-Extension#27]
In the code below, an `AggregateException` is caught and the original exception is rethrown:

```c#
try
{
    Parallel.ForEach(someEnumerable, DoWork);
}
catch (AggregateException ex)
{
    throw ex.Flatten().InnerExceptions.First();
}
```

Incidentally, `InnerExceptions` is a collection of `Exception`, so ReCommended warns here that `Exception` should not be thrown - a more specific exception should be used. Do you agree that the warning doesn't really fit here?

**Comment by michael-damatov** [comment]
The ReCommended doesn't have any knowledge about the exact exception, it only sees the `Exception` object being thrown.
