### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by megakid** [prodot/ReCommended-Extension#3]
A couple of suggestions - I am going to try to setup an IDE for Resharper development but can't seem to get it to work at the moment, else I would create a PR.

Would love to see some or all of the following - some ideas if anyone is interested:
- Warn against `DateTime.Now` - replace with `DateTime.UtcNow`.  Also applies to `DateTime.Today`.  This is to avoid clock change issues.
- A R#r 10 version of these:  https://github.com/hazzik/ReSharper.DictionaryHelper/

**Comment by michael-damatov** [comment]
Using `DateTime.Now` (`DateTime.Today` as well) is not bad per se. It isn't a code smell.

**Comment by michael-damatov** [comment]
It is not a trivial task to determine from the context whether considering clock changes was intended or not. So this part (`DateTime.Now`, `DateTime.Today`) probably won't be done.

**Comment by michael-damatov** [comment]
According to the provided sample I conclude that the only analyzer provided by the [DictionaryHelper](https://github.com/hazzik/ReSharper.DictionaryHelper) is `ContainsKey` followed by the indexer getter. Is it correct?

**Comment by megakid** [comment]
Fair enough on the `DateTime` suggestion, that's probably more of a team convention rather than a universal one.

Yes the `DictionaryHelper` is indeed to fix up `ContainsKey` followed by the `indexer` - sometimes it genuinely makes the code more readable but typically laziness and wasteful.

**Comment by michael-damatov** [comment]
Well, a simple pattern is relatively easy to detect:

    if (dictionary.ContainsKey(key))
    {
        var value = dictionary[key]
    }

It would also make sense to detect the _negated_ pattern:

    if (!dictionary.ContainsKey(key))
    {
        // ...
    }
    else
    {
        var value = dictionary[key]
    }

The `if` condition can also be composed of multiple expressions:

    if (/*...*/ && dictionary.ContainsKey(key) && /*...*/)
    {
        var value = dictionary[key]
    }

And, these expressions could be arbitrary complex.

I see two choices here:

- detect the simple (and the corresponding _inverted_) pattern and ignore the complex (simple solution)
- use the control flow analysis (much more complex solution)

**Comment by megakid** [comment]
Correct me if I'm wrong but does it matter if there anything else in the if condition?

    if (/*...*/ && dictionary.ContainsKey(key) && /*...*/)
    {
        object value = dictionary[key]
    }

Is the same as (except 1 less dictionary look up in some cases - where the overall `if` condtion is `true`):
    
    object value;
    if (/*...*/ && dictionary.TryGetValue(key, out value) && /*...*/)
    {
        
    }

Is there really any difference between your two choices?


We also have another, even nastier dictionary access issue dotted around:

We have code such as this:

    if (dictionary.ContainsKey(key))
    {
        dictionary[key] = newValue;
    }
    else
    {
        dictionary.Add(key, newValue);
    }

This clearly highlights a lack of understanding of dictionaries as this can all be replaced with this:

    dictionary[key] = newValue;

Just another example of where static code analysis can help.  (Not saying we should fix this issue here)

**Comment by megakid** [comment]
Thinking a bit more about it, I seems to me that `ContainsKey` should only ever be used when the `indexer` isn't used afterwards.  Otherwise `TryGetValue` is always a better option.  Would you agree?

**Comment by michael-damatov** [comment]
The following example

    if (/*...*/ && dictionary.ContainsKey(key) && /*...*/)
    {
        object value = dictionary[key]
    }

is just a special case that is very relatively simple because it consists of subexpression all combined with the AND relation. In a more general case we could also have OR relations and non-trivial (and deeply nested) parentheses around any kind of expressions. That's what I mean with arbitrary complex.

The next example:

    if (dictionary.ContainsKey(key))
    {
        dictionary[key] = newValue;
    }
    else
    {
        dictionary.Add(key, newValue);
    }

represents another pattern. Please create a separate issue for it.

**Comment by michael-damatov** [comment]
Agree that the `TryGetValue` is always the better choice than the `ContainsKey` followed by the indexer getter.

**Comment by megakid** [comment]
I understand it could be deeply nested and arbitrarily complex with `||` and `&&` but I still think that a flatout replacement of `ContainsKey` with `TryGetValue` would be acceptable in all by the most nuanced (I can't think of one).  The `out` variable declaration needs to be above the if condition statement.  I probably don't understand the complexities involved in PSI and spotting these conditions but it seems it could be reasonably achievable?

**Comment by michael-damatov** [comment]
You're right the flatout replacement of `ContainsKey` with `TryGetValue` would be acceptable for most `IDictionary` implementations that are not thread-safe. We should be careful with the `ConcurrentDictionary`.

**Comment by megakid** [comment]
Here's another bad practice.   Just putting this here as it's all part of `Dictionary` refactors.

                        if (dict.ContainsKey(key))
                        {
                            dict.Remove(key);
                        }

Replaced with just:

    dict.Remove(key);

**Comment by michael-damatov** [comment]
Several "breaking" statements should also be considered, e.g.

    if (!dict.ContainsKey(key))
    {
        break; // "continue", "throw", or "return"
    }
    var value = dictionary[key]
