### ISSUE TITLE
False positive for xUnit assertions

### ISSUE THREAD

**Issue by zvirja** [prodot/ReCommended-Extension#32]
I have the following snippet of code in my tests:
```c#
[Fact]
public void SutShouldBeASpecimenBuilder()
{
    // Arrange
    var sut = new EnumRangedRequestRelay();

    // Act & Assert
    Assert.IsAssignableFrom<ISpecimenBuilder>(sut);
}
```

However, due to some reasons, extension says that assertion is redundant:
![image](https://user-images.githubusercontent.com/1074182/33824723-ff3c50f8-de67-11e7-9093-10c9ad0e8429.png)

Likely, you incorrectly recognize the Assert statements and their logic.

**Comment by michael-damatov** [comment]
Could you share a sample solution?

**Comment by zvirja** [comment]
@michael-damatov Sorry for the belated reply - was busy and after that had holidays.

Sure, here is the sample.

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```

Test file:
```c#
using System.Collections;
using System.Collections.Generic;
using Xunit;

namespace RecommendedExtensionBugDemo
{
  public class DemoTest
  {
    [Fact]
    public void ShouldNotShowWarning()
    {
      var list = new List<string>();
      Assert.IsAssignableFrom<IEnumerable>(list);
    }
  }
}
```

Result:
![image](https://user-images.githubusercontent.com/1074182/34876004-5e77a56e-f7a8-11e7-84cd-9a1a550983f3.png)

I would like to have a unit test that particular object implements interface and it's not a redundant assertion. Moreover, if I follow the TDD, that's might the only test that could require me to inherit the interface. Probably, you should modify the heuristic to omit such kind of warnings.

**Comment by michael-damatov** [comment]
Sorry, but I see no simple way to implement such a heuristic.

I suggest to suppress the inspection at the method or class level.

**Comment by zvirja** [comment]
Could you please clarify what exactly is the purpose of this suggestion? This is the unit test, so obviously if I write assertion, I need it to document the code. Why do you suggest to remove it?

**Comment by zvirja** [comment]
@michael-damatov Could you please follow up?

**Comment by michael-damatov** [comment]
The analyzer suggests to remove the assertion; the suggestion is obviously wrong in the context of unit tests.

So my idea was to suppress the suggestion with the `[SuppressMessage]` attribute. The attribute can be placed at the method or at the class level.
