### ISSUE TITLE
What are the warnings for  "async void"?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [prodot/ReCommended-Extension#36]
I want to check how "async void"  warning is shown https://github.com/prodot/ReCommended-Extension/wiki/Avoid-Async-Void. 
I am running v1.0.7 on VS2015 and getting

> 'async void' public surface area method without detected usage. 

and 
> 'async void' public surface area method with detected usage. 

Is it expected behaviour? It doesn't describe why it is wrong and why I should avoid it.

**Comment by michael-damatov** [comment]
The behavior is fully expected.

- http://theburningmonk.com/2012/10/c-beware-of-async-void-in-your-code/
- https://www.filipekberg.se/2012/09/20/avoid-shooting-yourself-in-the-foot-with-tasks-and-async/
- https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Tip-1-Async-void-is-for-top-level-event-handlers-only
