### ISSUE TITLE
Package creation docs

### ISSUE THREAD

**Issue by 0xorial** [prodot/ReCommended-Extension#37]
I immediately apologize for my silly question, but...
I used projects structure from here to create my own [R# extension](https://github.com/0xorial/ForceTaskObserve). I managed to get it to R# gallery, but now I need to compile it against a newer R# SDK. Unfortunately, I cannot get "nuget pack" command working with the "{{}}" syntax in the [.nuspec](https://github.com/prodot/ReCommended-Extension/blob/master/Sources/ReCommendedExtension.Deployment/ReCommendedExtension.nuspec).
I am getting an error:
'{{AssemblyFileVersion}}' is not a valid version string.

I did not manage to find any documentation for this kind of syntax in .nuspec file. 
Which command do you use to build the package?

P.S. What drives me mad is the fact that I apparently managed to build it some long time ago, but now I am stuck...

**Comment by michael-damatov** [comment]
These are placeholders.

I run the [Deployment](https://github.com/prodot/ReCommended-Extension/tree/master/Sources/ReCommendedExtension.Deployment) program to generate packages. It replaces the placeholders with correct data.
