### ISSUE TITLE
Redundant Captured Context (ConfigureAwait(false)) suggested incorrectly

### ISSUE THREAD

**Issue by meganaut** [prodot/ReCommended-Extension#41]
I have a case similar to this example:

```
async Task<bool> SomeFunction()
{
    var someLock = await GetTheLock();

    try {
        return await SomeCodeThatMayThrow();
    }
    finally {
        await someLock.Release();
    }
}
```

I believe it is incorrect to recommend the `return await SomeCodeThatMayThrow` line should have ConfigureAwait(false) because the finally section will run afterwards.

**Comment by michael-damatov** [comment]
This issue has been fixed with the [Release 3.5.0](https://github.com/prodot/ReCommended-Extension/releases/tag/v3.5.0). Please install the latest version.
