### ISSUE TITLE
2019.3.1 Version

### ISSUE THREAD

**Issue by Mike-EEE** [prodot/ReCommended-Extension#42]
I attempted to install this extension for 2019.3.1 but was unable to do so.

Please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

Thank you for any assistance you can provide towards this matter.

**Comment by michael-damatov** [comment]
Just released the [v4.0.0 (RC1)](https://github.com/prodot/ReCommended-Extension/releases/tag/v4.0.0-RC1). The version was built for ReSharper 2019.3.1.

You can download and install it from a local directory, or wait until it becomes available on the ReSharper Gallery (usually up 2 business days).

**Comment by Mike-EEE** [comment]
Great, thank you @michael-damatov!

**Comment by Mike-EEE** [comment]
Hi @michael-damatov I am not yet seeing this in ReSharper Gallery when looking for extensions... has this been deployed for 2019.3.1?

**Comment by michael-damatov** [comment]
The current version is still a pre-release. Make sure you've checked the "Include prerelease packages" in the ReSharper Options dialog (s. Environment/Extension Manager).

**Comment by Mike-EEE** [comment]
Wow!  I had no idea... you would think that such an important checkbox would be right there in the extension manager UI. 😲 😞

That worked like a charm, though.  Thanks again for your patience and assistance, @michael-damatov. 👍
