### ISSUE TITLE
Question: Avoid local suppression

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#43]
Why it is considered as warning by default ?
What is the correct way to suppress then ?

**Comment by michael-damatov** [comment]
No justification is required for local suppressions, however, suppressing if at method/type level (with the `[SuppressMessage]` attribute) would require to put a justification, although it's not checked to be correct.

The correct ways to suppress it:
* it at the method or type level (with the `[SuppressMessage]` attribute);
* open the ReSharper Options/Code Inspection/Inspection Severity, locate the rule, and change its severity (or even turn it off).
