### ISSUE TITLE
Inspection together with InspectTool

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#46]
Is it possible to run inspections together with JetBrains InspectTool?

**Comment by michael-damatov** [comment]
I've never tried this before. However, according to [Use ReSharper extensions with InspectCode﻿](https://www.jetbrains.com/help/resharper/InspectCode.html#using-extensions-with-inspectcode) it should be possible.

**Comment by NN---** [comment]
Wow , i need to download nupkg.
I wonder whether nuget supports this.
Also I need to download nupkg from JetBrains gallery somehow.
Do you have a clue how to make it possible ?

**Comment by michael-damatov** [comment]
You can download any version from the [online gallery](https://plugins.jetbrains.com/plugin/11646-recommended-extension-for-resharper) or from the [GitHub Release page](https://github.com/prodot/ReCommended-Extension/releases).

**Comment by NN---** [comment]
I understand.
I mean how to do it using CLI nuget.exe .

**Comment by NN---** [comment]
Can you upload your nuget package to nuget.org ?

**Comment by NN---** [comment]
https://youtrack.jetbrains.com/issue/RSRP-436208

**Comment by michael-damatov** [comment]
The nuget.org is not the appropriate repository for ReSharper extensions.

**Comment by NN---** [comment]
Ok.
Do you know what is the nuget repository url to install from manually?

**Comment by michael-damatov** [comment]
https://plugins.jetbrains.com/plugin/11646-recommended-extension-for-resharper
