### ISSUE TITLE
await Task.From*

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#47]
There is no point requiring ConfigureAwait(false) for Task.FromResult, Task.FromException, Task.FromCanceled and so on.

**Comment by michael-damatov** [comment]
Fully agree, it doesn't make any sense to add `ConfigureAwait(...)` for method not running asynchronously.

However, there is no generic way for the analyzer to know whether a `Task`-returning method running asynchronously or not. A conceivable approach could be to have a list of "well-known" methods, but methods from third-party libraries will always be missing.

On the other side, it doesn't happen very often that `async` `Task`-returning methods really use `Task.From(...)` methods. The general approach is actually using inside a non-`async` `Task`-returning methods or properties.

The effort of implementing this feature outweighs the potential benefits.
