### ISSUE TITLE
How to suppress inspections globally ?

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#49]
How do I suppress inspections in assembly.
I tried the naïve approach but it doesn't work.

```cs
[assembly: SuppressMessage("ReSharper", "AsyncConverter.ConfigureAwaitHighlighting", Scope = "NamespaceAndDescendants", Target = "A")]

// This doesn't work either
[assembly: SuppressMessage("ReSharper", "AsyncConverter.ConfigureAwaitHighlighting", Scope = "type", Target = "A.Q")]

namespace A
{
    class Q
    {
        async void F()
        {
            await File.ReadAllTextAsync("a");
        }
    }
}
```

**Comment by michael-damatov** [comment]
To suppress an inspection at the assembly level requires the support by the ReSharper.

You can, however, disable the inspection at the solution level. Just open the ReSharper options, go to the "Inspection Severity", find the inspection, and turn it off. Make sure to save the option for the solution (personal or team-shared).

Could this workaround help you?

**Comment by NN---** [comment]
Solution level is not good since I want to disable only certain inspections for certain projects.

**Comment by NN---** [comment]
Found the ReSharper issue, didn't know the problem is there.
https://youtrack.jetbrains.com/issue/RSRP-463998
