### ISSUE TITLE
Add check for raising exceptions in unexpected locations

### ISSUE THREAD

**Issue by zwitbaum** [prodot/ReCommended-Extension#5]
Please add check for violation of the [CA1065: Do not raise exceptions in unexpected locations](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations).

**Comment by michael-damatov** [comment]
### Current Limitations

* Only _immediate_ `throw` expressions and statements are checked. Exceptions thrown by called methods are not checked.
* The `Dispose(false)` code path is checked regardless it actually called by the finalizer.
