### ISSUE TITLE
Add support for Rider 2020.2

### ISSUE THREAD

**Issue by mvonballmo** [prodot/ReCommended-Extension#51]
**Use Case**

I'm using Visual Studio with ReSharper and consider the Recommended extension a must-have. I'm evaluating a move to Rider, but have noticed that I would have to leave this extension behind.

**Comment by michael-damatov** [comment]
Adding support for Rider would require regular testing (on Rider) for all subsequent releases. You can, however, fork the repo to add the Rider support.

The effort of implementing this outweighs the potential benefits as there are no plans to use Rider.

**Comment by mvonballmo** [comment]
Ok. Thanks for taking the time to reply.
