### ISSUE TITLE
Add support for suggesting Async suffix in a method name

### ISSUE THREAD

**Issue by DevEngineReq** [prodot/ReCommended-Extension#53]
ReCommended-Extension should suggest me to add the Async suffix to an asynchronous method name

**Comment by michael-damatov** [comment]
"Asynchronous method" is a bit confusing here:

* a method with the `async` modifier
* an _awaitable_ method (that returns a `Task`, `Task<T>`, `ValueTask`, `ValueTask<T>`, or even `IAsyncEnumerable<T>`). Such a method don't have to have the `async` modifier to be _awaited_. You can also have awaitable properties (that are of the types listed above).

The effort of adding such a feature to the "ReCommended Extension" definitely outweighs the potential benefits. Please, take a look at other extensions.

_Side note:_
Historically, the "Async" suffix was added to new awaitable methods (that return `Task` or `Task<T>`) to distinguish between older non-awaitable methods. When designing new classes, which consist only of awaitable methods, what is the added value making all method names simply longer?
