### ISSUE TITLE
[Question] HttpRequestException

### ISSUE THREAD

**Issue by NN---** [prodot/ReCommended-Extension#54]
Why throwing HttpRequestException is prohibited ?

**Comment by michael-damatov** [comment]
According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestexception) the `HttpRequestException` is the base* class for exceptions thrown by the `HttpClient`** and `HttpMessageHandler`** classes.

*I could not find any derived class in the .NET Framework (checked v4.8 and v5.0.1). The exception class is not sealed, so any library can define derived classes.
** The exception is supposed to be thrown by `HttpClient` and `HttpMessageHandler`. Actually, there shouldn't be any reason to throw the exception.

Do you have a good reason to throw the `HttpRequestException`?

**Comment by NN---** [comment]
Yeah I wondered too where are derived classes:)
I just used it in my test.
